# Generated by Django 3.2.9 on 2021-11-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_user_id', models.IntegerField()),
                ('name', models.TextField()),
                ('shift_types', models.TextField(unique=True)),
                ('leaves_per_worker', models.IntegerField()),
                ('workhours_per_worker', models.IntegerField()),
                ('global_total_shifts', models.IntegerField()),
                ('global_remaining_shifts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('real_name', models.TextField()),
                ('password', models.TextField()),
                ('type', models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B'), ('C', 'Shift C')], default='A', max_length=255)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='UserShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('shift_dates', models.JSONField()),
                ('leave_dates', models.JSONField()),
                ('remainder_shifts', models.IntegerField()),
                ('year', models.IntegerField()),
                ('allocated_leaves', models.IntegerField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_user_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('choices', models.JSONField()),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organisation', to_field='shift_types')),
            ],
        ),
    ]
